apiVersion: v2
name: elchi-discovery
description: A Helm chart for Elchi Discovery
type: application
version: 1.0.0
appVersion: "1.0.0"
kubeVersion: ">=1.19.0-0"
keywords:
  - elchi
  - kubernetes
  - endpoint-discovery
  - cloud-native
home: https://github.com/CloudNativeWorks/elchi-helm
sources:
  - https://github.com/CloudNativeWorks/elchi-helm
maintainers:
  - name: CloudNativeWorks
    email: support@cloudnativeworks.io

annotations:
  artifacthub.io/license: MIT
  artifacthub.io/prerelease: "false"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/valuesSchema: "true"
  artifacthub.io/requirements: |
    - Kubernetes 1.19+
    - Helm 3.0.0+