apiVersion: v1
kind: ConfigMap
metadata:
  name: elchi-config
  namespace: {{ .Release.Namespace }}
data:
  config.js: |
    window.APP_CONFIG = {
      API_URL: "{{- if .Values.global.tlsEnabled }}https://{{- else }}http://{{- end }}{{ .Values.global.mainAddress }}{{- if and .Values.global.port (not (or (eq (toString .Values.global.port) "80") (eq (toString .Values.global.port) "443"))) }}:{{ .Values.global.port }}{{- end }}",
      API_URL_LOCAL: 'http://localhost:65190',
      ENABLE_DEMO: {{ .Values.global.enableDemo }},
      VERSION: "{{ .Values.image.tag }}",
      AVAILABLE_VERSIONS: [{{- $versions := list }}{{- range .Values.global.versions }}{{- $envoyVersion := regexFind "envoy[0-9]+\\.[0-9]+\\.[0-9]+" .tag | replace "envoy" "v" }}{{- $versions = append $versions $envoyVersion }}{{- end }}{{- range $index, $version := $versions }}{{- if $index }}, {{ end }}'{{ $version }}'{{- end }}]
    };
