apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  namespace: {{ $.Release.Namespace }}
  labels:
    app: victoriametrics
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8428
    protocol: TCP
    name: http
  selector:
    app: victoriametrics