apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: victoriametrics
  namespace: {{ $.Release.Namespace }}
  labels:
    app: victoriametrics
spec:
  serviceName: victoriametrics
  replicas: 1
  selector:
    matchLabels:
      app: victoriametrics
  template:
    metadata:
      labels:
        app: victoriametrics
    spec:
      containers:
      - name: victoriametrics
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if $.Values.global.timezone }}
        env:
        - name: TZ
          value: "{{ $.Values.global.timezone }}"
        {{- end }}
        ports:
        - containerPort: 8428
          name: http
        args:
        - -storageDataPath=/victoria-metrics-data
        - -retentionPeriod={{ .Values.retentionPeriod }}
        - -httpListenAddr=0.0.0.0:8428
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: storage
          mountPath: /victoria-metrics-data
        - name: timezone
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: timezone
        hostPath:
          path: /etc/localtime
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.persistence.storageClass }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }} 