apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: {{ $.Release.Namespace }}
  labels:
    app: otel-collector
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.grpcPort }}
    targetPort: 4317
    protocol: TCP
    name: grpc
  - port: {{ .Values.service.httpPort }}
    targetPort: 4318
    protocol: TCP
    name: http
  selector:
    app: otel-collector 