image:
  repository: jhonbrownn/elchi-backend
  pullPolicy: Always

resources:
  controller:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "2Gi"
      cpu: "2000m"
  controlPlane:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "4Gi"
      cpu: "1000m"
  registry:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "500m"

service:
  type: ClusterIP
  controller:
    port: 8099
    grpcPort: 50051
  controlPlane:
    port: 18000
  registry:
    port: 9090
    metricsPort: 9091

configMap:
  name: elchi-backend-config

config:
  logging:
    level: "info"
    formatter: "text"
    reportCaller: "false"
