image:
  repository: jhonbrownn/elchi-backend
  pullPolicy: Always

resources:
  controller:
    requests:
      memory: "64Mi"
      cpu: "25m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  controlPlane:
    requests:
      memory: "64Mi"
      cpu: "25m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  registry:
    requests:
      memory: "64Mi"
      cpu: "25m"
    limits:
      memory: "256Mi"
      cpu: "200m"

service:
  type: ClusterIP
  controller:
    port: 8099
    grpcPort: 50051
  controlPlane:
    port: 18000
  registry:
    port: 9090
    metricsPort: 9091

configMap:
  name: elchi-backend-config

config:
  logging:
    level: "info"
    formatter: "text"
    reportCaller: "false"
