image:
  repository: jhonbrownn/elchi-coredns
  tag: v0.1.1
  pullPolicy: Always

resources:
  requests:
    memory: "32Mi"
    cpu: "10m"
  limits:
    memory: "256Mi"
    cpu: "200m"

dns:
  port: 53
  bindAddress: "{$NODE_IP}"  # Injected via Downward API (status.hostIP)

forwarders:
  - "8.8.8.8"
  - "8.8.4.4"
