{{- if .Values.global.installMongo }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: mongodb-service
  labels:
    app: mongodb
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    app: mongodb
{{- end }} 