{{- if .Values.global.installGslb }}
apiVersion: v1
kind: Service
metadata:
  name: elchi-coredns
  namespace: {{ .Release.Namespace }}
  labels:
    app: elchi-coredns
    {{- include "elchi-coredns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.dnsPort }}
      targetPort: {{ .Values.service.dnsPort }}
      protocol: UDP
      name: dns-udp
    - port: {{ .Values.service.dnsPort }}
      targetPort: {{ .Values.service.dnsPort }}
      protocol: TCP
      name: dns-tcp
  selector:
    app: elchi-coredns
{{- end }}
